add test command to nixos-wifi-ap-eap

diff --git a/wifi-ap-eap/nixos-wifi-ap-eap-tail b/wifi-ap-eap/nixos-wifi-ap-eap-tail
--- a/wifi-ap-eap/nixos-wifi-ap-eap-tail
+++ b/wifi-ap-eap/nixos-wifi-ap-eap-tail
@@ -7,7 +7,7 @@
 # - CERTS_DIR
 # - SSID
 # - CLIENT_CERT_VALID_DAYS
-# - PATH with coreutils, sed, grep, pwgen, openssl, perl, zip
+# - PATH with coreutils, sed, grep, pwgen, openssl, perl, zip, unzip, eapol_test
 
 set -e
 
@@ -130,6 +130,72 @@ EOF
   echo "Certificate has been stored in $output"
 }
 
+cmd_client_test() {
+  zip="$1"
+  if [ -z "$zip" ] ; then
+    echo "Usage: $0 client test usercert.zip" >&2
+    echo ""
+    echo "The input file must be a ZIP file that has been generated by"
+    echo "`$0 client add ...`."
+    exit 1
+  fi
+  zip="$(realpath "$zip")"
+
+  umask 077
+  tmp="$(mktemp -d wifi_eap_client_testXXXXXXXX)"
+  cd "$tmp"
+  unzip "$zip"
+
+  identity="$(sed -n 's/^ *Identity: \(.*\)$/\1/p' README.txt)"
+  domain="$(sed -n 's/^ *Domain: \(.*\)$/\1/p' README.txt)"
+  if [ -z "$identity" -o -z "$domain" ] ; then
+    echo "ERROR: Couldn't extract identity and/ or domain from README.txt" >&2
+    echo "  Identity: $identity"
+    echo "  Domain:   $domain"
+    exit 1
+  fi
+
+  if [ ! -f "$identity.pem" ] ; then
+    echo "ERROR: User certificate not found: $identity.pem" >&2
+    exit 1
+  fi
+  if [ ! -f "$domain.pem" ] ; then
+    echo "ERROR: Server certificate not found: $domain.pem" >&2
+    exit 1
+  fi
+
+  RADIUS_SECRET="$(sed -n 's/secret *= *//p' "$SECRETS_DIR/client-secret.conf")"
+  if [ -z "$RADIUS_SECRET" ] ; then
+    echo "ERROR: Couldn't get radius secret from $SECRETS_DIR/client-secret.conf" >&2
+    exit 1
+  fi
+
+  read -s -p "Password for user key: " pw
+
+  echo "$pw" >pw
+  if ! openssl rsa -in "$identity.pem" -passin file:pw </dev/null | grep -q "BEGIN RSA PRIVATE KEY" ; then
+    echo "ERROR: Couldn't decrypt $identity.pem. Wrong password?" >&2
+    exit 1
+  fi
+
+  cat >config <<EOF
+    network={
+      eap=TLS
+      key_mgmt=IEEE8021X
+      identity="$identity"
+      client_cert="$identity.pem"
+      private_key="$identity.pem"
+      private_key_passwd="$pw"
+      ca_cert="$domain.pem"
+    }
+EOF
+
+  EAPOL_TEST_SECRET="$RADIUS_SECRET" eapol_test -c config -p 18120
+
+  cd ..
+  rm -r "$tmp"
+}
+
 cmd_client_list() {
   case "$1" in
     --raw)
@@ -243,6 +309,7 @@ cmd_client_listcrl() {
 
 help() {
   echo "$0 client add ...    : generate certificate for client"
+  echo "$0 client test ...   : test certificate for client"
   echo "$0 client list       : list existing certificates"
   echo "$0 client revoke     : revoke client certificate"
   echo "$0 client listcrl    : show certificate revocation list"
@@ -250,7 +317,7 @@ help() {
 }
 
 case "$1 $2" in
-  "client add" | "client list" | "client revoke" | "client listcrl" | "client updatecrl")
+  "client add" | "client test" | "client list" | "client revoke" | "client listcrl" | "client updatecrl")
     cmd=cmd_$1_$2
     shift; shift
     $cmd "$@"
